### PR TITLE
fix(sqllogictest): add missing tokio `rt-multi-thread` feature

### LINKED ISSUE #2385: `cargo test -p iceberg-sqllogictest` fails to compile: missing tokio `rt-multi-thread` feature
### Apache Iceberg Rust version

None

### Describe the bug

Running `cargo test -p iceberg-sqllogictest` in isolation fails to compile with:

```bash
error[E0599]: no function or associated item named `new_multi_thread`
found for struct `tokio::runtime::Builder`
--> crates/sqllogictest/tests/sqllogictests.rs:28:39
```

`tests/sqllogictests.rs` calls `tokio::runtime::Builder::new_multi_thread()`, which requires the `tokio` `rt-multi-thread` feature. But `crates/sqllogictest/Cargo.toml` declares `tokio = { workspace = true }`, and the workspace root sets default-features = false with no features - so `rt-multi-thread` is never enabled for this crate.

### To Reproduce

```bash
git clone https://github.com/apache/iceberg-rust
cd iceberg-rust
cargo test -p iceberg-sqllogictest
```

### Expected behavior

The crate should compile and tests should run successfully when built in isolation.

Note: the bug is invisible with `make build` (`--all-features --workspace`) because `crates/examples` enables `tokio = { features = ["full"] }`, and Cargo features are additive across the workspace graph.

### Willingness to contribute

I can contribute a fix for this bug independently

### PR DESCRIPTION
**Pull request by toutane**
## Which issue does this PR close?

- Closes #2385 .

## What changes are included in this PR?

`crates/sqllogictest/Cargo.toml` was missing the `rt-multi-thread` feature for tokio, while `tests/sqllogictests.rs` calls `tokio::runtime::Builder::new_multi_thread()` which requires it.

This meant `cargo test -p iceberg-sqllogictest` failed to compile when run in isolation. The issue was invisible when using `make build`                                       (`--all-features --workspace`) because `crates/examples` already enables                                        `tokio = { features = ["full"] }`, and Cargo features are additive across                                       the workspace graph.

## Are these changes tested?

```sh
cargo test -p iceberg-sqllogictest
```

### CODE REVIEW

File: crates/sqllogictest/Cargo.toml [hunk 1]
```diff
@@ -39,7 +39,7 @@ sqllogictest = { workspace = true }
 toml = { workspace = true }
 serde = { workspace = true }
 tracing = { workspace = true }
-tokio = { workspace = true }
+tokio = { workspace = true, features = ["rt-multi-thread"] }
```
Comment (blackmwk) [inline crates/sqllogictest/Cargo.toml:42]: Should we also use `full` features?

Comment (toutane) [reply crates/sqllogictest/Cargo.toml:42]: `rt-multi-thread` is the only feature required here (`Builder::new_multi_thread()`).

Using `full` would also fix the bug.

**Review by kevinjqliu — APPROVED** [review]
LGTM ty!

**Comment by kevinjqliu** [comment]
> The issue was invisible when using make build (--all-features --workspace) because crates/examples already enables tokio = { features = ["full"] }, and Cargo features are additive across the workspace graph.

might be worth fixing this in case there are other similar issues

**Comment by kevinjqliu** [comment]
opened #2389, CI should fail in that CI because the tokio fix isnt included

**Review by CTTY — APPROVED** [review]
LGTM, thanks for the fix!
